config/routes.rb
Rails.application.routes.draw do
  resources :countries
  # resources :destinations
  resources :streets
  # resources :countries
  resources :users
  root to: 'home#index'
  
  # RESTful Routes (generated by scaffold)

  # TODO: sessions routes (see /controllers/sessions_controller.rb)
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'

  # TODO: add/drop courses routes (see /controllers/registrations_controller.rb)

  get '/delete', to: 'users#destroy'
  delete '/delete', to: 'users#destroy'
  post "/users/:user_id/edit", to: 'users#edit'
  post "/add_street/:user_id/:street_id", to: 'destinations#add_street'

  # post '/courses/:course_id', to: 'courses#show'
  # post "/add_course/:user_id/:course_id", to: 'registrations#add_course'
  # delete "/drop_course/:user_id/:course_id", to: 'registrations#drop_course'
  #
  # get "/drop_course/:user_id/:course_id", to: 'registrations#drop_course'

get '/countries_get_regions', to: 'countries#get_regions' 
get '/countries_get_cities', to: 'countries#get_cities' 
end

app/models/user.rb
class User < ApplicationRecord
  require 'bcrypt'
  include BCrypt
  has_many :destinations, dependent: :destroy
  has_many :streets, through: :destinations


  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, uniqueness: true, presence: true
  validates :password_hash, presence: true



  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end

  def full_name
    "#{first_name} #{last_name}"
  end

  def users
    User.all
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user, only: %i[index show]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @street = Street.new
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    @user = User.find_by(id: params[:id])
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)
    @user.password= user_params[:password_hash]
    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    @user = User.find(params[:id])
    oldpassword = @user.password_hash
    @user.assign_attributes(user_params)
    if user_params[:password_hash] != oldpassword
      @user.password = user_params[:password_hash]
    end

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :password_hash)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  <% if @user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :username, style: "display: block" %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :password_hash, style: "display: block" %>
    <%= form.text_field :password_hash %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_map.html.erb
<html>
<div id="map">
</div>
<style>
    #map{
        height:700px;
        width:100%;
    }
</style>
<script>

    function initAutocomplete() {
        const map = new google.maps.Map(document.getElementById("map"), {
            center: { lat: 0, lng: 30 },
            zoom: 2,
            mapTypeId: "roadmap",
        });

        // Create the search box and link it to the UI element.
        const input = document.getElementById("pac-input");
        const searchBox = new google.maps.places.SearchBox(input);

        map.addListener("bounds_changed", () => {
            searchBox.setBounds(map.getBounds());
        });

        let markers = [];

        // Listen for the event fired when the user selects a prediction and retrieve
        // more details for that place.
        searchBox.addListener("places_changed", () => {
            const places = searchBox.getPlaces();
            if (places.length == 0) {
                return;
            }
            // For each place, get the icon, name and location.
            const bounds = new google.maps.LatLngBounds();

            places.forEach((place) => {
                if (!place.geometry || !place.geometry.location) {
                    console.log("Returned place contains no geometry");
                    return;
                }

                document.getElementById('name').textContent += place.formatted_address;
                document.getElementById('latitude').textContent += place.geometry['location'].lat();
                document.getElementById('longitude').textContent += place.geometry['location'].lng();

                var marker = new google.maps.Marker({
                    position: place.geometry.location,
                    map:map
                });
                markers.push(marker);

                if (place.geometry.viewport) {
                    // Only geocodes have viewport.
                    bounds.union(place.geometry.viewport);
                } else {
                    bounds.extend(place.geometry.location);
                }
            });
            map.fitBounds(bounds);
        });

        let marks = [];
        var table = document.getElementById("table"), rIndex, cIndex;
        for (var i = 0; i  < table.rows.length; i++){
            console.log("reached");
            var lat = table.rows[i].cells[1].innerText;
            var long = table.rows[i].cells[2].innerText;
            let marker = new google.maps.Marker({
                position: new google.maps.LatLng(lat,long),
                map:map
            });
            markers.push(marker);
        }

    }


    window.initAutocomplete = initAutocomplete;
</script>


<!--<script  defer-->
<!--        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD5UU8paF_r2V1m4SF_G1ugD7olOGsSICw&libraries=places&callback=initAutocomplete">-->
<!--</script>-->
<!--<script-->
<!--  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD5UU8paF_r2V1m4SF_G1ugD7olOGsSICw&callback=initMap&v=weekly"-->
<!--   defer>-->
<!--</script>-->

<script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD5UU8paF_r2V1m4SF_G1ugD7olOGsSICw&callback=initAutocomplete&libraries=places&v=weekly"
     defer>
</script>

</script>
</html>

app/views/users/_table.html.erb
<table class="table">
  <thead class="thead-dark">
  <tr>
    <th scope="col">#</th>
    <th scope="col">Streets</th>
  </tr>
  </thead>
  <tbody>
<%Street.all.each_with_index do |street, index| %>

  <% if current_user.streets.include?(street) %>
      <tr>
        <th scope="row"><% index %></th>
        <td><%= street.street_name %></td>
      </tr>
  <% end %>
<% end %>
  </tbody>
</table>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>


  <p>
    <strong>Username:</strong>
    <%= user.username %>
  </p>

  <p>
    <strong>Password hash:</strong>
    <%= user.password_hash %>
  </p>

</div>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show Traveller", @user %> |
  <%= link_to "Back to Travellers", users_path %>
  <%= link_to "Delete Account", delete_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>
<style>
    h1 {font-family: Avenir, fantasy;}
    h2 {font-family: Avenir, fantasy; font-size: 20px; color: white; font-weight: bold}
    h5 {font-family: Avenir, fantasy; font-size: 20px; color: #01256e; font-weight: bold}
    h6 {font-family: Avenir, fantasy; font-size: 17px; color: #01256e;}
    h7 {font-family: Avenir, fantasy; font-size: 20px; font-weight: bold}
    h9 {font-family: Avenir, fantasy; font-size: 17px; }
    h10 {font-family: Avenir, fantasy; font-size: 17px; color:white}
</style>

<h1> Travellers </h1>
<!--<p>-->
<!--<a class="btn btn-primary" href="<%#= new_user_path %>"  role ="button"> New User </a>-->
<!--</p>-->

<div class = "row row-cols-1 row-cols-md-2">
  <% @users.each do |user| %>

    <div class="col mb-4">
        <div class="card" style="width: 18rem;">
          <div class="card-body">
            <p> <h5 class="card-title mb-2"> <%= user.first_name + " " + user.last_name %>
          <% if current_user.eql? user %>
            (Current User)
            <% end %>
          </h5> </p>
    <p>
      <a class="btn btn-outline-primary btn-sm" href="<%= user_path(user) %>"  role ="button"> User Info </a>
    </p>

    </div>
    </div>
    </div>
  <% end %>
    </div>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <a class ="btn btn-outline-primary btn-sm"  href= "<%= users_path %>" role = "button"> Back to Users </a>
</div>

app/views/users/show.html.erb
<html>

<head>
  <title>My Map</title>
  <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>

  <link rel="stylesheet" type="text/css" href="./style.css" />
  <script type="module" src="index.js"></script>
</head>
<body>
<h1> <%= @user.full_name %>'s Travels</h1>

<table id="table">
  <thead class="thead-dark">
  <tr>
    <th scope="col">Streets</th>
    <th scope="col">Latitude</th>
    <th scope="col">Longitude</th>
  </tr>
  </thead>
  <tbody>

  <% Street.all.each_with_index do |street, index| %>

    <% if @user.streets.include?(street) %>
      <tr>
        <td><%= street.street_name %></td>
        <td><%= street.latitude %></td>
        <td><%= street.longitude %></td>
      </tr>
    <% end %>
  <% end %>
  </table>






<!--  <div id="map">-->
<!--  </div>-->
<!--<script-->
<!--  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD5UU8paF_r2V1m4SF_G1ugD7olOGsSICw&callback=initAutocomplete&libraries=places&v=weekly"-->
<!--  defer>-->
<!--</script>-->
<br>
  <%= render "map" %>
<br>

<input id="pac-input" class="controls" style="height: 50px; width: 80%;" type="text" placeholder="Add Travel Destination" />
  <%= render "streets/form", street: @street %>


  <script>
    // var table = document.getElementById("table"), rIndex, cIndex;
    // for (var i = 0; i  < table.rows.length; i++){
    //     table.rows[i][1]
    //     for (var j = 0; j < table.rows[i].cells.length; j++){
    //
    //     }
    // }
  </script>

  <%# @user.streets do |street, index| %>

<!--      <tr>-->
<!--        <th scope="row"><%# index %></th>-->
<!--        <td><%#= street.street_name %></td>-->
<!--      </tr>-->
  <%# end %>
  </tbody>
</table>

<% render "table" %>
<%#= form_with model: @street do |form| %>
<!--  <div id = "name">-->
    <%#= form.label :street_name, style: "display: block" %>
    <%#= form.number_field :street_name %>
<!--  </div>-->
<!--  <div id = "latitude">-->
    <%#= form.label :latitude, style: "display: block" %>
    <%#= form.number_field :latitude %>
<!--  </div>-->
<!--  <div id = "longitude">-->
    <%#= form.label :longitude, style: "display: block" %>
    <%#= form.number_field :longitude %>
<!--  </div>-->
<!--  <div>-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>

<!--<div id="name" type="text"> </div>-->
<!--<div id="latitude" type="text" > </div>-->
<!--<div id="longitude" type="text"> </div>-->






<script>




</script>

<%# street = Street.create(city: z, longitude: x, latitude: y) %>





</body>

</html>

<!--<p style="color: green"><%#= notice %></p>-->
<!--<style>-->
<!--    h1 {font-family: Avenir, fantasy;}-->
<!--    h5 {font-family: Avenir, fantasy; font-size: 20px; color: #01256e; font-weight: bold}-->
<!--    h6 {font-family: Avenir, fantasy; font-size: 17px; color: #01256e;}-->
<!--    h7 {font-family: Avenir, fantasy; font-size: 20px; font-weight: bold}-->
<!--    h9 {font-family: Avenir, fantasy; font-size: 17px; }-->
<!--</style>-->

<!--<h1> User Info</h1>-->

<%#= render @user %>

<!--<div class="col-md-12 bg-light text-right ">-->
<!--  <h5>-->
    <%# if current_user.eql? @user %>
<!--      <a class="btn btn-outline-primary" href="<%#= edit_user_path(current_user) %>"  role ="button"> Edit User</a>-->

<!--      button_to "Edit this user", edit_user_path(@user), method: :post  --->
    <%# end %>
<!--    <a class="btn btn-outline-primary" href="<%#= users_path %>"  role ="button"> Back to Users</a>-->
<!--      </h5>-->

<!--</div>-->

<!--<p>-->
<%# if @user.is_instructor %>
<!--  <h5> Courses Teaching</h5>-->
  <%# end %>
<%# unless @user.is_instructor %>
<!--  <h5> Courses Taking </h5>-->
  <%# end %>
<!--</p>-->

<!--<div class = "row row-cols-1 row-cols-md-2">-->
  <%# Street.all.each do |course| %>
<!--    <div class="col mb-4">-->
      <%# if current_user.streets.include?(course) %>

<!--      <div class="card" style="width: 18rem;">-->
<!--        <div class="card-body">-->
<!--          <p> <h5 class="card-title mb-2"> <%#= street.street_name %> </h5> </p>-->


<!--          button_to "Course Info", course_path(course)  -->
<!--          <a class = "btn btn-outline-primary btn-sm" href=" <%#= course_path(course) %>" role="button"> Course Info </a>-->

          <%# if (current_user.eql? @user) && !(course.instructor.eql? @user)  %>
<!--            <a class ="btn btn-outline-primary btn-sm"  href="/drop_course/<%#= current_user.id %>/<%#= course.id %>"-->
<!--               role = "button"> Drop Course </a>-->
          <%# end %>
          <%# if course.instructor.eql? current_user %>
<!--            <a href="#" class="card-link">-->
              <%#= button_to "Edit", edit_course_path(course) %>
<!--            </a>-->
          <%# end %>
<!--        </div>-->
        <%# end %>
<!--      </div>-->
<!--    </div>-->

  <%# end %>
<!--</div>-->