config/routes.rb
Rails.application.routes.draw do
  resources :countries
  # resources :destinations
  resources :streets
  # resources :countries
  resources :users
  root to: 'home#index'
  
  # RESTful Routes (generated by scaffold)

  # TODO: sessions routes (see /controllers/sessions_controller.rb)
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'

  # TODO: add/drop courses routes (see /controllers/registrations_controller.rb)

  get '/delete', to: 'users#destroy'
  delete '/delete', to: 'users#destroy'
  post "/users/:user_id/edit", to: 'users#edit'
  post "/add_street/:user_id/:street_id", to: 'destinations#add_street'

  # post '/courses/:course_id', to: 'courses#show'
  # post "/add_course/:user_id/:course_id", to: 'registrations#add_course'
  # delete "/drop_course/:user_id/:course_id", to: 'registrations#drop_course'
  #
  # get "/drop_course/:user_id/:course_id", to: 'registrations#drop_course'

get '/countries_get_regions', to: 'countries#get_regions' 
get '/countries_get_cities', to: 'countries#get_cities' 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'My Travels', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if logged_in? %>
          <li class="nav-item">
            <%=  link_to 'My Page', "/users/#{current_user.id}", class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%=  link_to 'Streets', streets_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%=  link_to 'Traveller Pages', users_path, class:"nav-link"  %>
          </li>
          <li class="nav-item"><a class="dropdown item"></a>
            <%=  link_to 'Log Out', logout_path, method: :delete, class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%=  link_to 'Edit Profile', "/users/#{current_user.id}/edit", class:"nav-link"  %>
          </li>
        <%  else  %>
          <li class="nav-item">
            <%=  link_to 'Sign Up', new_user_path, class:"nav-link"  %>
          </li>
          <li class="nav-item">
            <%=  link_to 'Log In', login_path, class:"nav-link"  %>
          </li>
        <%  end %>

      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="/docs/4.0/assets/img/favicons/favicon.ico">

  <title>Cover Template for Bootstrap</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/cover/">

  <!-- Bootstrap core CSS -->
  <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="cover.css" rel="stylesheet">
</head>

<body class="text-center">

<!--<div id="back" class="view">-->
<!--  <div class="full-bg-img"></div>-->
<!--</div>-->

<!--<div class="bg-image" style = "background-image: url('https://wallpaperaccess.com/full/758246.jpg'); height: 100px" ></div>-->
<div class="cover-container d-flex h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h3 class="masthead-brand"></h3>
      <h3 class="masthead-brand"></h3>
      <h3 class="masthead-brand"></h3>
      <h3 class="masthead-brand"></h3>
      </nav>
    </div>
  </header>


  <main role="main" class="inner cover">
    <h1 class="cover-heading"> My Travels </h1>
    <p class="lead">A social way to see your friend's favorite travel destinations. Store! Share!</p>
    <p class="lead">
      <a href="/users/new" class="btn btn-lg btn-primary"> Bring Back The Memories </a>
    </p>
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p> Made by Jon Wong</p>
    </div>
  </footer>
</div>


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="../../assets/js/vendor/popper.min.js"></script>
<script src="../../dist/js/bootstrap.min.js"></script>
</body>
</html>