config/routes.rb
Rails.application.routes.draw do
  resources :countries
  # resources :destinations
  resources :streets
  # resources :countries
  resources :users
  root to: 'home#index'
  
  # RESTful Routes (generated by scaffold)

  # TODO: sessions routes (see /controllers/sessions_controller.rb)
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
  delete '/logout', to: 'sessions#destroy'
  post '/login', to: 'sessions#create'

  # TODO: add/drop courses routes (see /controllers/registrations_controller.rb)

  get '/delete', to: 'users#destroy'
  delete '/delete', to: 'users#destroy'
  post "/users/:user_id/edit", to: 'users#edit'
  post "/add_street/:user_id/:street_id", to: 'destinations#add_street'

  # post '/courses/:course_id', to: 'courses#show'
  # post "/add_course/:user_id/:course_id", to: 'registrations#add_course'
  # delete "/drop_course/:user_id/:course_id", to: 'registrations#drop_course'
  #
  # get "/drop_course/:user_id/:course_id", to: 'registrations#drop_course'

get '/countries_get_regions', to: 'countries#get_regions' 
get '/countries_get_cities', to: 'countries#get_cities' 
end

app/models/street.rb
class Street < ApplicationRecord
  belongs_to :country
  # has_one :country
  has_many :destinations, dependent: :destroy
  has_many :users, through: :destinations

  validates :country, presence: true
  validates :latitude, presence: true
  validates :longitude, presence: true
  validates :street_name, presence: true

end

app/controllers/streets_controller.rb
class StreetsController < ApplicationController
  before_action :set_street
  before_action :authenticate_user

  # skip_before_action :verify_authenticity_token
  # GET /streets or /streets.json
  def index
    @streets = Street.all
  end


  # GET /streets/1 or /streets/1.json
  def show
  end

  # GET /streets/new
  def new
    @street = Street.new
  end

  # GET /streets/1/edit
  def edit
  end

  # POST /streets or /streets.json
  def create
    @street = Street.new(street_params)
    # @street.user_id = params[:street][:user_id]

       if @street.save
         @current_user = current_user
         flash[:notice] = "Successfully added!"

         # render text: @street.street_name
       end
    # respond_to do |format|
    #   if @street.save
    #     @current_user = current_user
    #     format.html { redirect_to street_url(@street), notice: "Street was successfully created." }
    #     format.json { render :show, status: :created, location: @street }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @street.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /streets/1 or /streets/1.json
  def update
    @street = Street.find(params[:id])
    @street.assign_attributes(street_params)
    respond_to do |format|
      if @street.save
        format.html { redirect_to street_url(@street), notice: "Street was successfully updated." }
        format.json { render :show, status: :ok, location: @street }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @street.errors, status: :unprocessable_entity }
      end
    end


    # respond_to do |format|
    #   if @street.update(street_params)
    #     format.html { redirect_to street_url(@street), notice: "Street was successfully updated." }
    #     format.json { render :show, status: :ok, location: @street }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @street.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /streets/1 or /streets/1.json
  def destroy
    @street.destroy

    respond_to do |format|
      format.html { redirect_to streets_url, notice: "Street was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private


    # Use callbacks to share common setup or constraints between actions.
    def set_street
      @street = Street.find_by(street_name: params[:street_name])
    end

    # Only allow a list of trusted parameters through.
    def street_params
      params.require(:street).permit(:country_id, :city, :street_name, :latitude, :longitude)
      # params.require(:street).permit(:country_id, :city, :street_name, :longitude, :latitude)
    end
end

app/helpers/streets_helper.rb
module StreetsHelper
end

app/views/streets/_form.html.erb
<h1> Enter Street to Save on Your Map </h1>
<h5> <div id = "name">Street Name: </div> </h5>
<h5> <div id = "latitude">Latitude: </div> </h5>
<h5><div id = "longitude">Longitude: </div> </h5>
<%= form_with model: @street do |form| %>
  <% if @street.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(street.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% street.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :street_name, style: "display: block" %>
    <%= form.text_field :street_name %>
  </div>


  <div>
    <%= form.label :country_id, style: "display: block" %>
    <%= form.collection_select :country_id, Country.all, :id, :name %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
<!--     :value => @street.longitude-->
  </div>
  <div>
    <%= form.submit "Create Street", class:"btn btn-primary"%>
  </div>
<% end %>


<%#= form_with(model: street) do |form| %>
  <%# if street.errors.any? %>
<!--    <div style="color: red">-->
<!--      <h2><%#= pluralize(street.errors.count, "error") %> prohibited this street from being saved:</h2>-->

<!--      <ul>-->
        <%# street.errors.each do |error| %>
<!--          <li><%#= error.full_message %></li>-->
        <%# end %>
<!--      </ul>-->
<!--    </div>-->
  <%# end %>

<!--  <div>-->
    <%#= form.label :country_id, style: "display: block" %>
    <%#= form.text_field :country_id %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.label :city, style: "display: block" %>
    <%#= form.text_field :city %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.label :street_name, style: "display: block" %>
    <%#= form.text_field :street_name %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.label :location, style: "display: block" %>
    <%#= form.text_field :location %>
<!--  </div>-->

<!--  <div>-->
    <%#= form.submit %>
<!--  </div>-->
<%# end %>

app/views/streets/_street.html.erb
<div id="<%= dom_id street %>">
<!--  <p>-->
<!--    <strong>Country:</strong>-->
    <%#= street.country_id %>
<!--  </p>-->

  <p>
    <strong>Street name:</strong>
    <h5><%= street.street_name %></h5>
    <% if current_user.streets.include?(street) %>
    <p> <weak> Already in My Streets </weak></p>
      <% else %>
      <%=button_to "Add Street To My Travels", "/add_street/#{current_user.id}/#{street.id}", :method => :post,  class:"btn btn-primary btn-sm" %>
    <%end %>
  </p>


</div>

app/views/streets/edit.html.erb
<h1>Editing street</h1>

<%= render "form", street: @street %>

<br>

<div>
  <%= link_to "Show this street", @street %> |
  <%= link_to "Back to streets", streets_path %>
</div>

app/views/streets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Streets</h1>

<!--<div id="streets">-->
  <%# @streets.each do |street| %>
    <%#= render street %>
  <%# end %>
<!--</div>-->

<%#= link_to "New street", new_street_path %>



<div class = "row row-cols-1 row-cols-md-2">
  <% @streets.reverse.each do |street| %>

    <div class="col mb-4">
      <div class="card" style="width: 18rem;">
        <div class="card-body">
         <%= render street %>
      </div>
    </div>
    </div>
  <% end %>

</div>

app/views/streets/new.html.erb
<h1>New street</h1>

<%= render "form", street: @street %>

<br>

<div>
  <%= link_to "Back to streets", streets_path %>
</div>

app/views/streets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @street %>

<div>
  <%= link_to "Edit this street", edit_street_path(@street) %> |
  <%= link_to "Back to streets", streets_path %>

  <%= button_to "Destroy this street", @street, method: :delete %>
</div>